import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/Navigation";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{fontFamily:"'Open Sans', sans-serif"}}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
